const r1ques = [['What is the most common form factor?', 'What type of memory can you erase with UV light?', 'What does a berg connector attach to?', 'Is it possible to run multiple operating systems on a computer from different hard drives?', 'Is a dedicated or integrated graphics card better?', 'What is the first step to take if a computer will not turn on?'], ['ATX', 'EPROM', 'Floppy drive', 'Yes', 'Dedicated', 'Turn it on and off again']];
const r2ques = [['What does ZIF do?', 'What ROM contains instructions for the computer?', 'How many pins does the CPU power connector have?', 'Which is faster: SSD or HDD?', 'How many devices can a single USB port handle?', 'What switch do you check if a computer is not getting enough power?'], ['Helps protect pins on CPU', 'BIOS', '4/8', 'SSD', '127', '115V or 230V switch']];
const r3ques = [['What does the northbridge control?', 'What type of RAM do most laptops use?', 'How many pins does the motherboard power connector have?', 'Why is a blue laser better for reading optical drives?', 'What did AGP get replaced by?', 'What part of the computer is malfunctioning if the date and time are reset every time you start your computer?'], ['CPU, RAM, Graphics', 'SODIMM', '20', 'Shorter wavelength, more data', 'PCIe', 'CMOS']];
const r4ques = [['What is the acronym for the circuit board on a motherboard?', 'What is the fastest type of memory?', 'Is the inside of a SATA connector I shaped or L shaped?', 'How do you edit the password to access a hard drive?', 'What PCI do most dedicated graphics cards fit into?', 'What is a major component you never want to open in a computer?'], ['PCB', 'SRAM', 'L shaped', 'Access the BIOS settings during startup', 'PCIx16', 'Power supply']];
const r5ques = [['DAILY DOUBLE: When was the first motherboard released?', 'How many pins does a stick of DDR4 have?', 'What is the acronym for the ethernet cable?', 'What is the maximum capacity of a flash drive currently?', 'How many pins does a PCIx16 slot have?', 'What do you do if you become the IT person in your family?'], ['1981', '288', 'RJ-45', '2 TB', '82', 'Flee']];

function noMore(id) {
    var item = document.getElementById(id);
    item.classList.add('.dsb');
}